# Generated by Django 4.2.2 on 2023-06-15 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес автомойки', 'verbose_name_plural': 'Адреса автомоек'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Авто', 'verbose_name_plural': 'Авто'},
        ),
        migrations.AlterModelOptions(
            name='carclass',
            options={'verbose_name': 'Класс авто', 'verbose_name_plural': 'Классы авто'},
        ),
        migrations.AlterModelOptions(
            name='checkout',
            options={'verbose_name': 'Заказ услуги', 'verbose_name_plural': 'Заказы услуг'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='serviceprice',
            options={'verbose_name': 'Стоимость услуги', 'verbose_name_plural': 'Стоимости услуг'},
        ),
        migrations.AlterModelOptions(
            name='serviceuserloyalty',
            options={'verbose_name': 'Лояльность пользователя', 'verbose_name_plural': 'Лояльности пользователей'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес автомойки'),
        ),
        migrations.AlterField(
            model_name='address',
            name='map_coordinates',
            field=models.CharField(max_length=100, verbose_name='Координаты на карте'),
        ),
        migrations.AlterField(
            model_name='serviceuserloyalty',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='serviceuserloyalty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
    ]
