# Generated by Django 4.2.2 on 2023-06-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_address_options_alter_car_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='car_class',
            new_name='car',
        ),
    ]
