# Generated by Django 4.2.2 on 2023-06-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_car_class_customuser_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер телефона'),
        ),
    ]
