# Generated by Django 4.2.2 on 2023-07-17 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_paymenttype_checkout_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='final_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Полная стоимость заказа'),
        ),
    ]
